# Generated by Django 5.2.4 on 2025-08-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('auction_name', models.CharField(max_length=200)),
                ('item_name', models.CharField(max_length=200)),
                ('lot_number', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('lead', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('auction_site_estimate', models.CharField(blank=True, max_length=100)),
                ('ai_estimate', models.CharField(blank=True, max_length=100)),
                ('ai_description', models.TextField(blank=True)),
                ('researcher_estimate', models.CharField(blank=True, max_length=100)),
                ('researcher_description', models.TextField(blank=True)),
                ('reference_urls', models.JSONField(default=list)),
                ('photographer_quantity', models.IntegerField(default=1)),
                ('photographer_images', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('research', 'Research'), ('waiting', 'Waiting'), ('winning', 'Winning'), ('photography', 'Photography'), ('research2', 'Research 2'), ('finalized', 'Finalized')], default='research', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auction_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ebay_title', models.TextField(blank=True)),
                ('ebay_description', models.TextField(blank=True)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('ai_improved_estimate', models.TextField(blank=True)),
                ('ai_improved_description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
                ('raw_data', models.JSONField(default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'webhook_data',
                'ordering': ['-received_at'],
            },
        ),
    ]
